name: publish-dns

on:
  push:
    branches:
      - main
        #    paths:
        #      - '*.yaml'
        #      - '*.yml'

env:
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

jobs:
  publish-dns:
    name: Publish DNS changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14
      - name: Build nix-shell environment
        run: nix-shell --run 'echo nix-shell environment built!'
      - name: Sync DNS changes (./bin/sync)
        run: nix-shell --run './bin/sync'
